.PHONY : pdf clean 

pdf: homework.tex sec
	xelatex homework.tex 
	
clear: 
	rm *.log *.out *.synctex.gz *.fdb_latexmk *.aux *.fls *.xdv

clean: 
	rm *.log *.out *.synctex.gz *.fdb_latexmk *.aux *.fls *.xdv *.pdf
